### PR TITLE
Fix: (plz) Expand as-filename

### PR DESCRIPTION
**Pull request by josephmturner**
See [this hyperdrive.el issue](https://todo.sr.ht/~ushin/ushin/208).

### CODE REVIEW

**Comment by josephmturner** [comment]
[b6280f5](https://github.com/alphapapa/plz.el/pull/63/commits/b6280f5217fd2272471f36e212d38057dab1923e) started as an attempt to consolidate the `(pcase as ...)` forms, but it became evident that the simplest way to consolidate the logic involved adding a new mini-feature.  WDYT? :)

**Comment by josephmturner** [comment]
Force-push tidied up `(append (list (cons 'a 'b)) (list (cons 'c 'd)) ...)` into `(append (list (cons 'a 'b) (cons 'c 'd)) ...)`.

**Comment by alphapapa** [comment]
Released in v0.9.1.  Thanks.

**Comment by alphapapa** [comment]
Note, some "surgery" was done on the repository due to a bad merge commit I accidentally made in the process of merging this and #64.  So GitHub doesn't recognize the history correctly, but this PR is merged in v0.9.1.

**Pull request closed without merging**
